import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { User } from "@clerk/nextjs/dist/api";
import type { Park } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api } from "~/utils/api";

const PLACEHOLDER_THUMBNAIL_URL = "https://source.unsplash.com/random/640x360";

const ParkMenuSelection = (props: Park) => {
  const thumbnailURL = props.thumbnailUrl ?? PLACEHOLDER_THUMBNAIL_URL;
  return (
    <div className="">
      <Image
        className=" "
        src={thumbnailURL}
        alt="The thumbnail for the park"
        width={640}
        height={360}
      />
      <div>
        <span>{props.name}</span>
      </div>
    </div>
  );
};

// create a react component that loops through the users and displays them
const UserList = () => {
  const { data } = api.users.getAll.useQuery();
  return (
    <div>
      {data?.map((user) => (
        <div key={user.id}>{JSON.stringify(user)}</div>
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.users.getAll.useQuery();
  const { data: parkData } = api.parks.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen justify-center ">
          <div className="  w-full border-x-2 md:max-w-4xl">
            <div className="">
              <div className="flex justify-center border-b-2 p-2">
                <div>Your Parks</div>
                <div>{!user.isSignedIn && <SignInButton />}</div>
                {/* <div>{!!user.isSignedIn && <SignOutButton />}</div> */}
              </div>
              <div className="grid-flow-row grid-cols-2 gap-4">
                {parkData?.map((park) => (
                  <ParkMenuSelection {...park} key={park.id} />
                ))}
              </div>

              <UserList />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
